### Crear un libro
POST http://127.0.0.1:5000/libros
Content-Type: application/json

{
  "titulo": "El Principito",
  "autor": "Antoine de Saint-Exupéry",
  "isbn": "9789876420845",
  "categoria": "Ficción",
  "estado": "disponible"
}

### Obtener todos los libros
GET http://127.0.0.1:5000/libros

### Buscar por título
GET http://127.0.0.1:5000/libros/buscar?titulo=principito

### Obtener libro por ID
GET http://127.0.0.1:5000/libros/1

### Actualizar un libro
PUT http://127.0.0.1:5000/libros/1
Content-Type: application/json

{
  "titulo": "El Principito (edición especial)"
}

### Eliminar un libro
DELETE http://127.0.0.1:5000/libros/1
